/* Modelagem básica*/

CLIENTE

NOME CARACTER(30)
CPF NUMERICO(11)
EMAIL CARACTER(30)
TELEFONE CARACTER(30)
SEXO CARACTER(1)
ENDERECO CARACTER(100)

/* PROCESSO DE MODELAGEM*/

/* ADM DE DADOS*/
MODELAGEM CONCEITUAL-RASCUNHO 01
MODELAGEM LÓGICA- PROGRAMAS COM BRMODELO
/* AD - BDA*/
MODELAGEM FÍSICA- SCRIPT DO BANCO DE DADOS
/* Modelo físico */

/* criando um banco*/

CREATE DATABASE PROJETO;

/*CONECTANDO*/

USE PROJETO;

/*CRIANDO TABELA*/
CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11), 
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)

);
/*  VERIFICANDO AS TABELAS*/
SHOW TABLES;
/* DESCREVENDO TABELAS*/
DESC CLIENTE;